### ISSUE TITLE
SO MANY DEPENDENCIES

### ISSUE THREAD

**Issue by mtayler** [trstephen/elec300#1]
Literally taking longer to install dependencies than write the report.

**Comment by trstephen** [comment]
Solution: install Latex "big and beefy" version. Even the packages for knitting patterns. I thought you said you had the 10Gb install version :cake:

**Comment by mtayler** [comment]
Haha yeah I just recently nixed that in favour of `basictex`. MacTex is actually 14Gb!

And no kidding, pretty sure if my computer had hands MacTex could somehow bake a pie and knit a scarf.

**Comment by trstephen** [comment]
FYI I have a feeling the mactex installer gives you a couple flavors. There's the 14Gb "everything plus kitchen sink" and I feel like there's a ~2Gb version that I'm using. 

I could very well be mistaken. I set up my environment ~2 years ago and haven't updated since. I'm scared.
