### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by mtayler** [trstephen/elec300#4]
It would be really helpful writing the report if we could compile all our raw data somewhere, to reference when writing. I've got some data from the experiment but left it at home and got a chance to work right now, so I'm doing what I can but without some more data it's tough to draw conclusions.

@trstephen did you record what voltage the sources broke down at? I'm pretty sure I have it at home but it would be good to get some of the report done now.

**Comment by trstephen** [comment]
There's some data in the excel sheet, but not all of it. I'll upload some stuff with the data from the measurement sheet.

**Comment by trstephen** [comment]
Done 11f07d02aa841c667ac2d7cc38af3ce47a400db6

Sorry about that. I thought you had a copy of the data :fearful:

**Comment by mtayler** [comment]
Once again, thanks! Yeah I did, I just wasn't at home so I'd see if you were around to get it off you. Working on that first draft now.
